FROM openjdk:11 as builder

WORKDIR /payara

COPY .mvn/ ./.mvn/
COPY mvnw ./
COPY pom.xml ./

RUN ./mvnw dependency:resolve dependency:resolve-plugins

COPY src/ src/
RUN ./mvnw package -DskipTests

FROM gcr.io/distroless/java:11

COPY --from=amd64/busybox:1.31.1 /bin/busybox /busybox/busybox
RUN ["/busybox/busybox", "--install", "/bin"]

WORKDIR /payara

EXPOSE 8080 9090

ENV DB_HOST=weather-db DB_USER=payara DB_PASSWORD=1qay2wsx DB_NAME=weather

ENTRYPOINT ["java", "-server", "-Xshare:on", "-XX:SharedArchiveFile=payara.jsa", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=75.0", "-XX:ThreadStackSize=256", "-XX:MaxMetaspaceSize=128m", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=250", "-XX:+UseStringDeduplication", "-Djava.security.egd=file:/dev/./urandom", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=9090", "-Djava.rmi.server.hostname=localhost", "-Dcom.sun.management.jmxremote.rmi.port=9090", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.authenticate=false", "-jar", "micro-root/launch-micro.jar"]
CMD ["--nocluster", "--disablephonehome", "--deploy", "payara-weather-jar.war:/"]

COPY --from=builder /payara/target/payara-weather-jar-microbundle.jar ./
COPY --from=builder /payara/target/payara-weather-jar.war ./

# https://blog.payara.fish/warming-up-payara-micro-container-images-in-5.201
RUN java -jar payara-weather-jar-microbundle.jar --rootdir micro-root --outputlauncher && \
    rm -rf payara-weather-jar-microbundle.jar && \
    java -XX:DumpLoadedClassList=classes.lst -jar micro-root/launch-micro.jar --warmup && \
    java -Xshare:dump -XX:SharedClassListFile=classes.lst -XX:SharedArchiveFile=payara.jsa -jar micro-root/launch-micro.jar && \
    rm -rf classes.lst